### PR TITLE
 try fix get video src error

### PR DESCRIPTION
**Pull request by congzw**
try fix get video src error( because domId changed)

### CODE REVIEW

**Comment by vatz88** [comment]
Hey @congzw can you tell if your PR fixes #10 ? Also, if you can resolve merge conflicts.

**Comment by 0xShamil** [comment]
> Hey @congzw can you tell if your PR fixes #10 ? Also, if you can resolve merge conflicts.

Tested with the updated code. Seems to fix https://github.com/vatz88/Pluralsight-Course-Downloader/issues/10#issue-373327124

**Comment by vatz88** [comment]
Thanks @shamilchoudhury I'll resolve the conflicts and merge.

**Comment by vatz88** [comment]
#10 fixed

**Comment by congzw** [comment]
> Hey @congzw can you tell if your PR fixes #10 ? Also, if you can resolve merge conflicts.

yes!

**Pull request merged**
